// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Service.proto
// Protobuf Java Version: 4.26.1

package org.nott.grpc.service;

public final class Service {
  private Service() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Service.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_UserNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_UserNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_UserAgeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_UserAgeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_UserInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_UserInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_UserInfoResponseList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_nott_grpc_service_StreamResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_nott_grpc_service_StreamResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/Service.proto\022\025org.nott" +
      ".grpc.service\"#\n\017UserNameRequest\022\020\n\010user" +
      "name\030\001 \001(\t\" \n\014UserResponse\022\020\n\010realName\030\002" +
      " \001(\t\"\035\n\016UserAgeRequest\022\013\n\003age\030\001 \001(\005\">\n\020U" +
      "serInfoResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001" +
      "(\005\022\017\n\007address\030\003 \001(\t\"Y\n\024UserInfoResponseL" +
      "ist\022A\n\024userInfoResponseList\030\001 \003(\0132#.org." +
      "nott.grpc.service.UserResponse\" \n\rStream" +
      "Request\022\017\n\007request\030\001 \001(\t\"!\n\016StreamRespon" +
      "se\022\017\n\007request\030\001 \001(\t2\224\003\n\013UserService\022^\n\017G" +
      "etUserRealName\022&.org.nott.grpc.service.U" +
      "serNameRequest\032#.org.nott.grpc.service.U" +
      "serResponse\022_\n\013GetUserInfo\022%.org.nott.gr" +
      "pc.service.UserAgeRequest\032\'.org.nott.grp" +
      "c.service.UserInfoResponse0\001\022g\n\017GetUserI" +
      "nfoList\022%.org.nott.grpc.service.UserAgeR" +
      "equest\032+.org.nott.grpc.service.UserInfoR" +
      "esponseList(\001\022[\n\010BiStream\022$.org.nott.grp" +
      "c.service.StreamRequest\032%.org.nott.grpc." +
      "service.StreamResponse(\0010\001B\031\n\025org.nott.g" +
      "rpc.serviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_nott_grpc_service_UserNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_nott_grpc_service_UserNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_UserNameRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_org_nott_grpc_service_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_nott_grpc_service_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_UserResponse_descriptor,
        new java.lang.String[] { "RealName", });
    internal_static_org_nott_grpc_service_UserAgeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_nott_grpc_service_UserAgeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_UserAgeRequest_descriptor,
        new java.lang.String[] { "Age", });
    internal_static_org_nott_grpc_service_UserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_nott_grpc_service_UserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_UserInfoResponse_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", });
    internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_nott_grpc_service_UserInfoResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor,
        new java.lang.String[] { "UserInfoResponseList", });
    internal_static_org_nott_grpc_service_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_nott_grpc_service_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_StreamRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_org_nott_grpc_service_StreamResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_nott_grpc_service_StreamResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_nott_grpc_service_StreamResponse_descriptor,
        new java.lang.String[] { "Request", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
