// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Service.proto

// Protobuf Java Version: 4.26.1
package org.nott.grpc.service;

public interface StreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nott.grpc.service.StreamResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
