// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Service.proto

// Protobuf Java Version: 4.26.1
package org.nott.grpc.service;

/**
 * Protobuf type {@code org.nott.grpc.service.UserInfoResponseList}
 */
public final class UserInfoResponseList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:org.nott.grpc.service.UserInfoResponseList)
    UserInfoResponseListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      UserInfoResponseList.class.getName());
  }
  // Use UserInfoResponseList.newBuilder() to construct.
  private UserInfoResponseList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private UserInfoResponseList() {
    userInfoResponseList_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.nott.grpc.service.Service.internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.nott.grpc.service.Service.internal_static_org_nott_grpc_service_UserInfoResponseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.nott.grpc.service.UserInfoResponseList.class, org.nott.grpc.service.UserInfoResponseList.Builder.class);
  }

  public static final int USERINFORESPONSELIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.nott.grpc.service.UserResponse> userInfoResponseList_;
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.nott.grpc.service.UserResponse> getUserInfoResponseListList() {
    return userInfoResponseList_;
  }
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.nott.grpc.service.UserResponseOrBuilder> 
      getUserInfoResponseListOrBuilderList() {
    return userInfoResponseList_;
  }
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  @java.lang.Override
  public int getUserInfoResponseListCount() {
    return userInfoResponseList_.size();
  }
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  @java.lang.Override
  public org.nott.grpc.service.UserResponse getUserInfoResponseList(int index) {
    return userInfoResponseList_.get(index);
  }
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  @java.lang.Override
  public org.nott.grpc.service.UserResponseOrBuilder getUserInfoResponseListOrBuilder(
      int index) {
    return userInfoResponseList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < userInfoResponseList_.size(); i++) {
      output.writeMessage(1, userInfoResponseList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < userInfoResponseList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, userInfoResponseList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.nott.grpc.service.UserInfoResponseList)) {
      return super.equals(obj);
    }
    org.nott.grpc.service.UserInfoResponseList other = (org.nott.grpc.service.UserInfoResponseList) obj;

    if (!getUserInfoResponseListList()
        .equals(other.getUserInfoResponseListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUserInfoResponseListCount() > 0) {
      hash = (37 * hash) + USERINFORESPONSELIST_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfoResponseListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.nott.grpc.service.UserInfoResponseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.nott.grpc.service.UserInfoResponseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.nott.grpc.service.UserInfoResponseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.nott.grpc.service.UserInfoResponseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.nott.grpc.service.UserInfoResponseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.nott.grpc.service.UserInfoResponseList)
      org.nott.grpc.service.UserInfoResponseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.nott.grpc.service.Service.internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.nott.grpc.service.Service.internal_static_org_nott_grpc_service_UserInfoResponseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.nott.grpc.service.UserInfoResponseList.class, org.nott.grpc.service.UserInfoResponseList.Builder.class);
    }

    // Construct using org.nott.grpc.service.UserInfoResponseList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (userInfoResponseListBuilder_ == null) {
        userInfoResponseList_ = java.util.Collections.emptyList();
      } else {
        userInfoResponseList_ = null;
        userInfoResponseListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.nott.grpc.service.Service.internal_static_org_nott_grpc_service_UserInfoResponseList_descriptor;
    }

    @java.lang.Override
    public org.nott.grpc.service.UserInfoResponseList getDefaultInstanceForType() {
      return org.nott.grpc.service.UserInfoResponseList.getDefaultInstance();
    }

    @java.lang.Override
    public org.nott.grpc.service.UserInfoResponseList build() {
      org.nott.grpc.service.UserInfoResponseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.nott.grpc.service.UserInfoResponseList buildPartial() {
      org.nott.grpc.service.UserInfoResponseList result = new org.nott.grpc.service.UserInfoResponseList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.nott.grpc.service.UserInfoResponseList result) {
      if (userInfoResponseListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          userInfoResponseList_ = java.util.Collections.unmodifiableList(userInfoResponseList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.userInfoResponseList_ = userInfoResponseList_;
      } else {
        result.userInfoResponseList_ = userInfoResponseListBuilder_.build();
      }
    }

    private void buildPartial0(org.nott.grpc.service.UserInfoResponseList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.nott.grpc.service.UserInfoResponseList) {
        return mergeFrom((org.nott.grpc.service.UserInfoResponseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.nott.grpc.service.UserInfoResponseList other) {
      if (other == org.nott.grpc.service.UserInfoResponseList.getDefaultInstance()) return this;
      if (userInfoResponseListBuilder_ == null) {
        if (!other.userInfoResponseList_.isEmpty()) {
          if (userInfoResponseList_.isEmpty()) {
            userInfoResponseList_ = other.userInfoResponseList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUserInfoResponseListIsMutable();
            userInfoResponseList_.addAll(other.userInfoResponseList_);
          }
          onChanged();
        }
      } else {
        if (!other.userInfoResponseList_.isEmpty()) {
          if (userInfoResponseListBuilder_.isEmpty()) {
            userInfoResponseListBuilder_.dispose();
            userInfoResponseListBuilder_ = null;
            userInfoResponseList_ = other.userInfoResponseList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            userInfoResponseListBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUserInfoResponseListFieldBuilder() : null;
          } else {
            userInfoResponseListBuilder_.addAllMessages(other.userInfoResponseList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.nott.grpc.service.UserResponse m =
                  input.readMessage(
                      org.nott.grpc.service.UserResponse.parser(),
                      extensionRegistry);
              if (userInfoResponseListBuilder_ == null) {
                ensureUserInfoResponseListIsMutable();
                userInfoResponseList_.add(m);
              } else {
                userInfoResponseListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.nott.grpc.service.UserResponse> userInfoResponseList_ =
      java.util.Collections.emptyList();
    private void ensureUserInfoResponseListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        userInfoResponseList_ = new java.util.ArrayList<org.nott.grpc.service.UserResponse>(userInfoResponseList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        org.nott.grpc.service.UserResponse, org.nott.grpc.service.UserResponse.Builder, org.nott.grpc.service.UserResponseOrBuilder> userInfoResponseListBuilder_;

    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public java.util.List<org.nott.grpc.service.UserResponse> getUserInfoResponseListList() {
      if (userInfoResponseListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(userInfoResponseList_);
      } else {
        return userInfoResponseListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public int getUserInfoResponseListCount() {
      if (userInfoResponseListBuilder_ == null) {
        return userInfoResponseList_.size();
      } else {
        return userInfoResponseListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public org.nott.grpc.service.UserResponse getUserInfoResponseList(int index) {
      if (userInfoResponseListBuilder_ == null) {
        return userInfoResponseList_.get(index);
      } else {
        return userInfoResponseListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder setUserInfoResponseList(
        int index, org.nott.grpc.service.UserResponse value) {
      if (userInfoResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.set(index, value);
        onChanged();
      } else {
        userInfoResponseListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder setUserInfoResponseList(
        int index, org.nott.grpc.service.UserResponse.Builder builderForValue) {
      if (userInfoResponseListBuilder_ == null) {
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.set(index, builderForValue.build());
        onChanged();
      } else {
        userInfoResponseListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder addUserInfoResponseList(org.nott.grpc.service.UserResponse value) {
      if (userInfoResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.add(value);
        onChanged();
      } else {
        userInfoResponseListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder addUserInfoResponseList(
        int index, org.nott.grpc.service.UserResponse value) {
      if (userInfoResponseListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.add(index, value);
        onChanged();
      } else {
        userInfoResponseListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder addUserInfoResponseList(
        org.nott.grpc.service.UserResponse.Builder builderForValue) {
      if (userInfoResponseListBuilder_ == null) {
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.add(builderForValue.build());
        onChanged();
      } else {
        userInfoResponseListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder addUserInfoResponseList(
        int index, org.nott.grpc.service.UserResponse.Builder builderForValue) {
      if (userInfoResponseListBuilder_ == null) {
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.add(index, builderForValue.build());
        onChanged();
      } else {
        userInfoResponseListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder addAllUserInfoResponseList(
        java.lang.Iterable<? extends org.nott.grpc.service.UserResponse> values) {
      if (userInfoResponseListBuilder_ == null) {
        ensureUserInfoResponseListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, userInfoResponseList_);
        onChanged();
      } else {
        userInfoResponseListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder clearUserInfoResponseList() {
      if (userInfoResponseListBuilder_ == null) {
        userInfoResponseList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        userInfoResponseListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public Builder removeUserInfoResponseList(int index) {
      if (userInfoResponseListBuilder_ == null) {
        ensureUserInfoResponseListIsMutable();
        userInfoResponseList_.remove(index);
        onChanged();
      } else {
        userInfoResponseListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public org.nott.grpc.service.UserResponse.Builder getUserInfoResponseListBuilder(
        int index) {
      return getUserInfoResponseListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public org.nott.grpc.service.UserResponseOrBuilder getUserInfoResponseListOrBuilder(
        int index) {
      if (userInfoResponseListBuilder_ == null) {
        return userInfoResponseList_.get(index);  } else {
        return userInfoResponseListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public java.util.List<? extends org.nott.grpc.service.UserResponseOrBuilder> 
         getUserInfoResponseListOrBuilderList() {
      if (userInfoResponseListBuilder_ != null) {
        return userInfoResponseListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(userInfoResponseList_);
      }
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public org.nott.grpc.service.UserResponse.Builder addUserInfoResponseListBuilder() {
      return getUserInfoResponseListFieldBuilder().addBuilder(
          org.nott.grpc.service.UserResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public org.nott.grpc.service.UserResponse.Builder addUserInfoResponseListBuilder(
        int index) {
      return getUserInfoResponseListFieldBuilder().addBuilder(
          index, org.nott.grpc.service.UserResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
     */
    public java.util.List<org.nott.grpc.service.UserResponse.Builder> 
         getUserInfoResponseListBuilderList() {
      return getUserInfoResponseListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        org.nott.grpc.service.UserResponse, org.nott.grpc.service.UserResponse.Builder, org.nott.grpc.service.UserResponseOrBuilder> 
        getUserInfoResponseListFieldBuilder() {
      if (userInfoResponseListBuilder_ == null) {
        userInfoResponseListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            org.nott.grpc.service.UserResponse, org.nott.grpc.service.UserResponse.Builder, org.nott.grpc.service.UserResponseOrBuilder>(
                userInfoResponseList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        userInfoResponseList_ = null;
      }
      return userInfoResponseListBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:org.nott.grpc.service.UserInfoResponseList)
  }

  // @@protoc_insertion_point(class_scope:org.nott.grpc.service.UserInfoResponseList)
  private static final org.nott.grpc.service.UserInfoResponseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.nott.grpc.service.UserInfoResponseList();
  }

  public static org.nott.grpc.service.UserInfoResponseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfoResponseList>
      PARSER = new com.google.protobuf.AbstractParser<UserInfoResponseList>() {
    @java.lang.Override
    public UserInfoResponseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserInfoResponseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfoResponseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.nott.grpc.service.UserInfoResponseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

