// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Service.proto

// Protobuf Java Version: 4.26.1
package org.nott.grpc.service;

public interface UserInfoResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nott.grpc.service.UserInfoResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  java.util.List<org.nott.grpc.service.UserResponse> 
      getUserInfoResponseListList();
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  org.nott.grpc.service.UserResponse getUserInfoResponseList(int index);
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  int getUserInfoResponseListCount();
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  java.util.List<? extends org.nott.grpc.service.UserResponseOrBuilder> 
      getUserInfoResponseListOrBuilderList();
  /**
   * <code>repeated .org.nott.grpc.service.UserResponse userInfoResponseList = 1;</code>
   */
  org.nott.grpc.service.UserResponseOrBuilder getUserInfoResponseListOrBuilder(
      int index);
}
