// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/Service.proto

// Protobuf Java Version: 4.26.1
package org.nott.grpc.service;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.nott.grpc.service.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 2;</code>
   * @return The realName.
   */
  java.lang.String getRealName();
  /**
   * <code>string realName = 2;</code>
   * @return The bytes for realName.
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
